# Change these first
owner: sakhalinfox # Your GitHub organization or username, where this repository lives
repo: orangepilldevuptime # The name of this repository

sites:
  - name: Nostr relay websocket connectivity check - wss://nostr.orangepill.dev
    check: "ws"
    url: wss://nostr.orangepill.dev
  - name: Nost Public Relay Response time - wss://nostr.orangepill.dev
    url: https://nostr.orangepill.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.orangepill.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Sakhalinfox/orangepilldevuptime/master/assets/logo.png
  name: Orangepill.dev Uptime Status
  theme: dark
  #introTitle: "**Upptime**"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: https://orangepill.dev
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
